image: python:3.6.1

variables:

stages:
    - build
    - release

build:
    stage: build
    image: benhowes/chromium-xvfb-make
    before_script:
        - npm install
    script:
        - npm run build
    artifacts:
        untracked: true
        expire_in: 1hour


release-image:
    stage: release
    dependencies:
        - build
    image: benhowes/bluemix-deploy:latest
    tags:
        - dind
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN code.zoetrope.io:4678

        - docker build -f Dockerfile -t code.zoetrope.io:4678/zconnect/device-simulator-frontend/image:latest .
        - docker push code.zoetrope.io:4678/zconnect/device-simulator-frontend/image:latest

    only:
        - tags
